# Generated by Django 5.0.3 on 2024-05-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
