# Generated by Django 5.0.3 on 2024-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(through='core.OrderItem', to='core.product'),
        ),
    ]
