# Generated by Django 5.0.3 on 2024-05-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_ordered_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_products',
            new_name='purchased_products',
        ),
    ]
